name: flutter_sync_engine_workspace
publish_to: none
environment:
  sdk: ^3.5.0

workspace:
  - packages/sync_engine
  - packages/sync_engine_generator
  - packages/sync_engine_drift

dev_dependencies:
  lints: ^6.0.0
